### PR TITLE
Add ignores for clion and visual studio

### PR DESCRIPTION
**Pull request by Rinzii**

### CODE REVIEW

**Review by karnkaul — COMMENTED** [review]
Do we really need such a huge gitignore? I'd rather keep every line meaningful and the total length small, than try to capture everything theoretically possible on any random machine.

**Comment by Rinzii** [comment]
A decent chunk of the items in the ignore are binary files that are generated by vs or user specific files. My mentality for adding these into the ignore is to simplify the commit process so you don't have to wade through hundreds of generated files vs made. Though I do agree I could better move through the ignore and remove the more specific items that were included in the ignore from github.

**Comment by karnkaul** [comment]
> My mentality for adding these into the ignore is to simplify the commit process so you don't have to wade through hundreds of generated files vs made.

Totally agree, and in fact I'm coming from an even more strict point of view: there should never be any files generated in the root directory, except for a handful of IDE related things that are required to be in the root (like `compile_commands.json`), and like `imgui.ini` (generated by Dear ImGui, intended to be local to the session). This is why the build directories have been configured out of source (in `out`), and `build` is also ignored, for folks who don't want to use presets. I could add logic in CMake that hard fails if an in-source build is attempted.

My reasoning for keeping `.gitignore` light is to be 100% aware of exactly what files are generated in our workflows and where, and only explicitly ignore the ones that we choose to, where we choose to (minimize wildcard catches).

**Comment by karnkaul** [comment]
@Rinzii So what are our next steps with this?

**Comment by Rinzii** [comment]
I’d say for now we can avoid doing a full blockage and add more to the ignore as we go along. If we get more contributors though I’d like to come back to this issue at a later date. For now though I’ll close the pr.

**Pull request closed without merging**
